server {
    listen 80;

    location /cache {
        alias /mnt/json_cache;
    }

    location /resources {
        alias /mnt/example_res;
    }

    location / {
        root   /usr/share/nginx/html/live-paper-viewer;
        try_files $uri $uri/ /index.html;
    }
}
